# Generación de metadatos ENSANUT

Se genera el archivo de metadatos necesario para el programa de preprocesamiento.

In [1]:
import pandas as pd
import ast

In [3]:
metadatos_ensanut = pd.read_csv('../data/ensanut/raw/21ensanut_a20_hias.csv', dtype=str)

In [4]:
metadatos_ensanut.head()

,subcategoria,var,var_alias,description,visibility,var_type,is_category,values,campo_unificado,class
0,SOCIO-ECONÓMICOS. LOCALIZACIÓN,folio_i,folio_i,Folio,visible,abierta,FALSE,"{'is_category': 'false', 'min': 0, 'max': 0}",folio_i,FALSE
1,SOCIO-ECONÓMICOS. LOCALIZACIÓN,entidad,entidad,Entidad,visible,options,TRUE,"{'is_category': 'true', 'options': {'1': '01 A...",entidad,FALSE
2,SOCIO-ECONÓMICOS. LOCALIZACIÓN,region,region,Region o zona de trabajo,visible,options,TRUE,"{'is_category': 'true', 'options': {'1': 'Paci...",region,FALSE
3,SOCIO-ECONÓMICOS. LOCALIZACIÓN,region_s,region_s,Region de Selección,visible,options,TRUE,"{'is_category': 'true', 'options': {'1': 'Paci...",region_s,FALSE
4,SOCIO-ECONÓMICOS. LOCALIZACIÓN,municipio,municipio,Municipio,visible,abierta,FALSE,"{'is_category': 'false', 'min': 0, 'max': 0}",municipio,FALSE

In [5]:
metadatos_ensanut['values_dict'] = metadatos_ensanut['values'].apply(lambda x: ast.literal_eval(x))
posibles_valores = pd.json_normalize(metadatos_ensanut['values_dict'].tolist(), max_level=0)
posibles_valores

,is_category,min,max,options,1,2,3,4,5,6,8
0,false,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,true,NaN,NaN,"{'1': '01 AGUASCALIENTES', '2': '02 BAJA CALIF...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,true,NaN,NaN,"{'1': 'Pacifico_Norte', '2': 'Frontera', '3': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,true,NaN,NaN,"{'1': 'Pacifico_Norte', '2': 'Frontera', '3': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,false,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
707,true,NaN,NaN,"{'1': 'Ninguno', '2': '1 vez', '3': '2 veces',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
708,true,NaN,NaN,"{'1': 'Ninguno', '2': '1 vez', '3': '2 veces',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
709,true,NaN,NaN,"{'1': 'Casi nunca (o nunca)', '2': 'Algunas ve...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
710,true,NaN,NaN,"{'1': 'Casi nunca (o nunca)', '2': 'Algunas ve...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
711,true,NaN,NaN,"{'1': 'Casi nunca (o nunca)', '2': 'Algunas ve...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# se crea una nueva columna de posibles valores, y otra de posibles valores pero con sus respectivos alias

metadatos_ensanut['posibles_valores_alias'] = metadatos_ensanut['values_dict'].apply(lambda x: list(x.get('options', {}).keys()))
metadatos_ensanut['posibles_valores'] = metadatos_ensanut['values_dict'].apply(lambda x: list(x.get('options', {}).values()))
metadatos_ensanut['posibles_valores_alias'] = metadatos_ensanut['posibles_valores_alias'].astype(str)
metadatos_ensanut['posibles_valores'] = metadatos_ensanut['posibles_valores'].astype(str)

In [ ]:
metadatos_ensanut['options'] = posibles_valores['options']

# se cambia el tipo de la variable municipio a options
metadatos_ensanut.loc[metadatos_ensanut['var'] == 'municipio', 'var_type'] = 'options'

metadatos_ensanut.head()

,subcategoria,var,var_alias,description,visibility,var_type,is_category,values,campo_unificado,class,values_dict,posibles_valores_alias,posibles_valores,options
0,SOCIO-ECONÓMICOS. LOCALIZACIÓN,folio_i,folio_i,Folio,visible,abierta,FALSE,"{'is_category': 'false', 'min': 0, 'max': 0}",folio_i,FALSE,"{'is_category': 'false', 'min': 0, 'max': 0}",[],[],NaN
1,SOCIO-ECONÓMICOS. LOCALIZACIÓN,entidad,entidad,Entidad,visible,options,TRUE,"{'is_category': 'true', 'options': {'1': '01 A...",entidad,FALSE,"{'is_category': 'true', 'options': {'1': '01 A...","['1', '2', '3', '4', '5', '6', '7', '8', '9', ...","['01 AGUASCALIENTES', '02 BAJA CALIFORNIA', '0...","{'1': '01 AGUASCALIENTES', '2': '02 BAJA CALIF..."
2,SOCIO-ECONÓMICOS. LOCALIZACIÓN,region,region,Region o zona de trabajo,visible,options,TRUE,"{'is_category': 'true', 'options': {'1': 'Paci...",region,FALSE,"{'is_category': 'true', 'options': {'1': 'Paci...","['1', '2', '3', '4', '5', '6', '7', '8', '9']","['Pacifico_Norte', 'Frontera', 'Pacifico_Centr...","{'1': 'Pacifico_Norte', '2': 'Frontera', '3': ..."
3,SOCIO-ECONÓMICOS. LOCALIZACIÓN,region_s,region_s,Region de Selección,visible,options,TRUE,"{'is_category': 'true', 'options': {'1': 'Paci...",region_s,FALSE,"{'is_category': 'true', 'options': {'1': 'Paci...","['1', '2', '3', '4', '5', '6', '7', '8', '9']","['Pacifico_Norte', 'Frontera', 'Pacifico_Centr...","{'1': 'Pacifico_Norte', '2': 'Frontera', '3': ..."
4,SOCIO-ECONÓMICOS. LOCALIZACIÓN,municipio,municipio,Municipio,visible,options,FALSE,"{'is_category': 'false', 'min': 0, 'max': 0}",municipio,FALSE,"{'is_category': 'false', 'min': 0, 'max': 0}",[],[],NaN

In [9]:
metadatos_ensanut['dtype'] = 'str'
metadatos_ensanut.head()

,subcategoria,var,var_alias,description,visibility,var_type,is_category,values,campo_unificado,class,values_dict,posibles_valores_alias,posibles_valores,options,dtype
0,SOCIO-ECONÓMICOS. LOCALIZACIÓN,folio_i,folio_i,Folio,visible,abierta,FALSE,"{'is_category': 'false', 'min': 0, 'max': 0}",folio_i,FALSE,"{'is_category': 'false', 'min': 0, 'max': 0}",[],[],NaN,str
1,SOCIO-ECONÓMICOS. LOCALIZACIÓN,entidad,entidad,Entidad,visible,options,TRUE,"{'is_category': 'true', 'options': {'1': '01 A...",entidad,FALSE,"{'is_category': 'true', 'options': {'1': '01 A...","['1', '2', '3', '4', '5', '6', '7', '8', '9', ...","['01 AGUASCALIENTES', '02 BAJA CALIFORNIA', '0...","{'1': '01 AGUASCALIENTES', '2': '02 BAJA CALIF...",str
2,SOCIO-ECONÓMICOS. LOCALIZACIÓN,region,region,Region o zona de trabajo,visible,options,TRUE,"{'is_category': 'true', 'options': {'1': 'Paci...",region,FALSE,"{'is_category': 'true', 'options': {'1': 'Paci...","['1', '2', '3', '4', '5', '6', '7', '8', '9']","['Pacifico_Norte', 'Frontera', 'Pacifico_Centr...","{'1': 'Pacifico_Norte', '2': 'Frontera', '3': ...",str
3,SOCIO-ECONÓMICOS. LOCALIZACIÓN,region_s,region_s,Region de Selección,visible,options,TRUE,"{'is_category': 'true', 'options': {'1': 'Paci...",region_s,FALSE,"{'is_category': 'true', 'options': {'1': 'Paci...","['1', '2', '3', '4', '5', '6', '7', '8', '9']","['Pacifico_Norte', 'Frontera', 'Pacifico_Centr...","{'1': 'Pacifico_Norte', '2': 'Frontera', '3': ...",str
4,SOCIO-ECONÓMICOS. LOCALIZACIÓN,municipio,municipio,Municipio,visible,options,FALSE,"{'is_category': 'false', 'min': 0, 'max': 0}",municipio,FALSE,"{'is_category': 'false', 'min': 0, 'max': 0}",[],[],NaN,str

In [ ]:
#metadatos_ensanut.to_csv('../data/ensanut/preprocessed/21ensanut_a20_hias_rework.csv')